// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform/helper/resource"
	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/tf"
)

func TestAccDataSourceAzureRMP2sVpnGateway_basic(t *testing.T) {
	dataSourceName := "data.azurerm_p2s_vpn_gateway.test"
	ri := tf.AccRandTimeInt()
	location := testLocation()

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:  func() { testAccPreCheck(t) },
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourceP2sVpnGateway_basic(ri, location),
				Check: resource.ComposeTestCheckFunc(
					resource.TestCheckResourceAttr(dataSourceName, "virtual_hub_id", "/subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4/resourceGroups/demo1-zhijie-westus2/providers/Microsoft.Network/virtualHubs/zhijie-vh-westus2"),
					resource.TestCheckResourceAttr(dataSourceName, "p2s_vpn_server_configuration_id", "/subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4/resourceGroups/demo1-zhijie-westus2/providers/Microsoft.Network/virtualWans/zhijie-vw-westus2/p2sVpnServerConfigurations/zhijie-p2scfg-westus2"),
					resource.TestCheckResourceAttr(dataSourceName, "vpn_client_address_pool_prefixes.#", "1"),
					resource.TestCheckResourceAttr(dataSourceName, "vpn_client_address_pool_prefixes.0", "101.3.0.0/16"),
				),
			},
		},
	})
}

func testAccDataSourceP2sVpnGateway_basic(rInt int, location string) string {
	config := testAccAzureRMP2sVpnGateway_basic(rInt, location)
	return fmt.Sprintf(`
%s

data "azurerm_p2s_vpn_gateway" "test" {
  resource_group_name = "${azurerm_p2s_vpn_gateway.test.resource_group_name}"
  name                = "${azurerm_p2s_vpn_gateway.test.name}"
}
`, config)
}
