// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform/helper/resource"
	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/tf"
)

func TestAccDataSourceAzureRMPrivateEndpoint_basic(t *testing.T) {
	// dataSourceName := "data.azurerm_private_endpoint.test"
	ri := tf.AccRandTimeInt()
	location := testLocation()

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:  func() { testAccPreCheck(t) },
		Providers: testAccProviders,
		Steps: []resource.TestStep{
			{
				Config: testAccDataSourcePrivateEndpoint_basic(ri, location),
				Check:  resource.ComposeTestCheckFunc(),
			},
		},
	})
}

func testAccDataSourcePrivateEndpoint_basic(rInt int, location string) string {
	config := testAccAzureRMPrivateEndpoint_basic(rInt, location)
	return fmt.Sprintf(`
%s

data "azurerm_private_endpoint" "test" {
  resource_group_name = "${azurerm_private_endpoint.test.resource_group_name}"
  name                = "${azurerm_private_endpoint.test.name}"
}
`, config)
}
