// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file at
//     https://github.com/Azure/magic-module-specs
//
// ----------------------------------------------------------------------------

package azurerm

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform/helper/resource"
	"github.com/hashicorp/terraform/terraform"
	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/helpers/tf"
	"github.com/terraform-providers/terraform-provider-azurerm/azurerm/utils"
)

func TestAccAzureRMPrivateEndpoint_basic(t *testing.T) {
	resourceName := "azurerm_private_endpoint.test"
	ri := tf.AccRandTimeInt()
	location := testLocation()

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testCheckAzureRMPrivateEndpointDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccAzureRMPrivateEndpoint_basic(ri, location),
				Check: resource.ComposeTestCheckFunc(
					testCheckAzureRMPrivateEndpointExists(resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "subnet_id"),
					resource.TestCheckResourceAttr(resourceName, "manual_private_link_service_connections.0.name", fmt.Sprintf("acctestconnection-%d", ri)),
					resource.TestCheckResourceAttrSet(resourceName, "manual_private_link_service_connections.0.private_link_service_id"),
				),
			},
			{
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccAzureRMPrivateEndpoint_complete(t *testing.T) {
	resourceName := "azurerm_private_endpoint.test"
	ri := tf.AccRandTimeInt()
	location := testLocation()

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testCheckAzureRMPrivateEndpointDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccAzureRMPrivateEndpoint_complete(ri, location),
				Check: resource.ComposeTestCheckFunc(
					testCheckAzureRMPrivateEndpointExists(resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "subnet_id"),
					resource.TestCheckResourceAttr(resourceName, "private_link_service_connections.0.name", fmt.Sprintf("acctestconnection-%d", ri)),
					resource.TestCheckResourceAttrSet(resourceName, "private_link_service_connections.0.private_link_service_id"),
					resource.TestCheckResourceAttr(resourceName, "private_link_service_connections.0.group_ids.#", "0"),
					resource.TestCheckResourceAttr(resourceName, "private_link_service_connections.0.request_message", "plz approve my request"),
					resource.TestCheckResourceAttr(resourceName, "tags.env", "test"),
				),
			},
			{
				Config: testAccAzureRMPrivateEndpoint_completeUpdate(ri, location),
				Check: resource.ComposeTestCheckFunc(
					testCheckAzureRMPrivateEndpointExists(resourceName),
					resource.TestCheckResourceAttrSet(resourceName, "subnet_id"),
					resource.TestCheckResourceAttr(resourceName, "private_link_service_connections.0.name", fmt.Sprintf("acctestconnection-%d", ri)),
					resource.TestCheckResourceAttrSet(resourceName, "private_link_service_connections.0.private_link_service_id"),
					resource.TestCheckResourceAttr(resourceName, "private_link_service_connections.0.group_ids.#", "0"),
					resource.TestCheckResourceAttr(resourceName, "private_link_service_connections.0.request_message", "plz approve my request"),
					resource.TestCheckResourceAttr(resourceName, "tags.env", "test"),
					resource.TestCheckResourceAttr(resourceName, "tags.version", "2"),
				),
			},
		},
	})
}

func testCheckAzureRMPrivateEndpointExists(resourceName string) resource.TestCheckFunc {
	return func(s *terraform.State) error {
		rs, ok := s.RootModule().Resources[resourceName]
		if !ok {
			return fmt.Errorf("Private Endpoint not found: %s", resourceName)
		}

		name := rs.Primary.Attributes["name"]
		resourceGroup := rs.Primary.Attributes["resource_group_name"]

		client := testAccProvider.Meta().(*ArmClient).network.PrivateEndpointClient
		ctx := testAccProvider.Meta().(*ArmClient).StopContext

		if resp, err := client.Get(ctx, resourceGroup, name, ""); err != nil {
			if utils.ResponseWasNotFound(resp.Response) {
				return fmt.Errorf("Bad: Private Endpoint %q (Resource Group %q) does not exist", name, resourceGroup)
			}
			return fmt.Errorf("Bad: Get on PrivateEndpointClient: %+v", err)
		}

		return nil
	}
}

func testCheckAzureRMPrivateEndpointDestroy(s *terraform.State) error {
	client := testAccProvider.Meta().(*ArmClient).network.PrivateEndpointClient
	ctx := testAccProvider.Meta().(*ArmClient).StopContext

	for _, rs := range s.RootModule().Resources {
		if rs.Type != "azurerm_private_endpoint" {
			continue
		}

		name := rs.Primary.Attributes["name"]
		resourceGroup := rs.Primary.Attributes["resource_group_name"]

		if resp, err := client.Get(ctx, resourceGroup, name, ""); err != nil {
			if !utils.ResponseWasNotFound(resp.Response) {
				return fmt.Errorf("Bad: Get on PrivateEndpointClient: %+v", err)
			}
		}

		return nil
	}

	return nil
}

func testAccAzureRMPrivateEndpoint_basic(rInt int, location string) string {
	return fmt.Sprintf(`
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-%d"
  location = "%s"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvnet-%d"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                              = "acctestsubnet-%d"
  resource_group_name               = "${azurerm_resource_group.test.name}"
  virtual_network_name              = "${azurerm_virtual_network.test.name}"
  address_prefix                    = "10.0.0.0/16"
  private_endpoint_network_policies = "Disabled"
}

resource "azurerm_private_endpoint" "test" {
  name                = "acctestendpoint-%d"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  subnet_id           = "${azurerm_subnet.test.id}"

  manual_private_link_service_connections {
    name                    = "acctestconnection-%d"
    private_link_service_id = "/subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4/resourceGroups/demo2-zhijie-westus2/providers/Microsoft.Network/privateLinkServices/zhijie-pls"
  }
}
`, rInt, location, rInt, rInt, rInt, rInt)
}

func testAccAzureRMPrivateEndpoint_complete(rInt int, location string) string {
	return fmt.Sprintf(`
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-%d"
  location = "%s"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvnet-%d"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                              = "acctestsubnet-%d"
  resource_group_name               = "${azurerm_resource_group.test.name}"
  virtual_network_name              = "${azurerm_virtual_network.test.name}"
  address_prefix                    = "10.0.0.0/16"
  private_endpoint_network_policies = "Disabled"
}

resource "azurerm_private_endpoint" "test" {
  name                = "acctestendpoint-%d"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  subnet_id           = "${azurerm_subnet.test.id}"

  private_link_service_connections {
    name                    = "acctestconnection-%d"
    private_link_service_id = "/subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4/resourceGroups/demo2-zhijie-westus2/providers/Microsoft.Network/privateLinkServices/zhijie-pls"
    group_ids               = []
    request_message         = "plz approve my request"
  }

  tags = {
    env = "test"
  }
}
`, rInt, location, rInt, rInt, rInt, rInt)
}

func testAccAzureRMPrivateEndpoint_completeUpdate(rInt int, location string) string {
	return fmt.Sprintf(`
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-%d"
  location = "%s"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvnet-%d"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                              = "acctestsubnet-%d"
  resource_group_name               = "${azurerm_resource_group.test.name}"
  virtual_network_name              = "${azurerm_virtual_network.test.name}"
  address_prefix                    = "10.0.0.0/16"
  private_endpoint_network_policies = "Disabled"
}

resource "azurerm_private_endpoint" "test" {
  name                = "acctestendpoint-%d"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
  subnet_id           = "${azurerm_subnet.test.id}"

  private_link_service_connections {
    name                    = "acctestconnection-%d"
    private_link_service_id = "/subscriptions/67a9759d-d099-4aa8-8675-e6cfd669c3f4/resourceGroups/demo2-zhijie-westus2/providers/Microsoft.Network/privateLinkServices/zhijie-pls"
    group_ids               = []
    request_message         = "plz approve my request"
  }

  tags = {
    env     = "test"
    version = "2"
  }
}
`, rInt, location, rInt, rInt, rInt, rInt)
}
